<?             //COMMBATS ,мусомbаts точка n e t 'imwar.ru'  легендарыбк ру 
$search = Array('gobk.ml','dawin.info','tinyurl.com','streets.world','resbk.ru','sbinfo.ru','gradebk.ru','razbk.ru','sebk.ru','onbk.ru','febk.ru','rbk.name','legbk.com','old-bk.net','resbk.com','oldcombats','olddil.ru','whclan.ru','rucombats.com','rebk.name','myncv.ru','losthero.ru','mygoldbk.com','legendbattles.ru','seosprint.net','newcombvirt','mygoldbk.com','world-chaos.ru','mircombats.com','silverbk','silver-bk.com','mycombk.ru','oldbbk.com','бк-2.рф','new.old-bk.net','goldbk.com','b23.ru','мирбк.рф','combvirt.сом','бойцовский-клуб2.рф','combats-old.ru','darkcombats.com','royalbattleclub.com', 'legrome.ru','mirbk.com','oldrome.ru','urlclick.ru','urls.by','mainwar.ru','bk2.ru','nura.biz','mycombats.net','r-bk.com','imperia.az','commbats','oldbatle.com','symbolofsunrise.clan.su','ccombats.net','oldbbk.com','maxbk','valorage.net','mircombats ','mycombats.net','snipurl.com','combbats.jimdo.com ','anti-neverlands.ru','ereality.ru','urla.ru','flq.us21e','altbk.gu.ma','ourcombats',
'last-battle.ru','newacap.ru','lifebk.Ru','rebk.do.am','mycombats.net','battle-kings.gu.ma','graпdсоmbаts.соm','lostbk.ru',
'ourcombats.net','hi.kgar2','parkvbg.ru','ancient-war.ru','is.gdXPBOg','fdworlds.net','new-era.3dn.ru',
'romewars.ru','fdworlds.net','cosmodark.ru','romewars.ru','ardaniya.ru','haddan.ru',
'territory','battleera',
'роялбаттлклаб','royalbattleclub','grandcombаts','erabk.ru','oldarena.ru','arenabk.ru',
'ow.lyajAEY','путя.рф','combats.cc','grandcombats.com','ancient-war.ru','onebk.ru','mystery-online.com',
'lastbk.ru','nsfw.in','warsclub.com','sheol.biz','sexbk','darktimes.com.ua','wildbk.ru','2me.me6e1d83',
'erepublik.com','kdreams.ru','7li.inBm0','wsaz.us','url.ief4kg','bklife.ru','clck.ru','war-bk.com','chaosage.ru',
'goo.gl54cgx','murl.kz','lostworlds.lv','legendarybk.ru','dragonar.ru',
'dwmq.gu.ma','scombats.ru','warsbk.ru','u.tovffpaq','warriorgame.ru','u.toldf4AQ','ow.ly9APVo','xcombats.com','sexbk.ru',
'dawnoffear.ru','is.gdbc7Or3','gamenet.ru','u.tola7daq',
'u.tolA7DAQ','neoldbk.com','deadly-club.ru','neoldbk.ru','old-nw.ru','lastcarnage.org','titans-island.com','ardaniy',
'genesyx','wolflands.ru','wildspace-online.ru','guild-honor.ru','obk.x7p.ru','magegame.ru','new-capital.in','stariybk.ru',
'ardaniya','devil-war.ru','netwars.ru','my-bk.ru','combasbk.com','torment.ru','cruelbk.ru','combatsbk.com',
'combatz11.eurovz.ru','vip-bk.ru','combats-old.ru','darkagesworld.com','combatz.biz','nextworld.ru','hop.kz',
'combat3.com','ourcombats.com','bloodyworld.com','rebk.ru','the-sinners.com','bestcombats.com','bkcombats.com',
'war-of-gods.ru','warcom.ucoz.ua','skyfamily.ru','dungeoncity.ru','mmorpg.su','shadow-of-combats.ru','combots.ru',
'drako.ru','pathofninja.ru','worldofchaos.ru','ark-game.ru','evocombats.co.cc','wglads.ru','world-fight.com',
'azwars.com','obk2.com','nyubk.ru','maziguga.ru ','titans-island.ru','warcombats.com','xcombats.ru','kombats2.com',
'windland.ru','seosprint.net','oldbk.ucoz.net','odessa-bk.ru','cruelwar.ru','cruel-world.ru','combk.net','eurocombats.co.cc',
'wmsite.ru','veng.do.am','polymorf.ru','lordal.zzx.su','draz.emo.su ','woffs.9pn.ru','bget.ru','elions.org',
'empireofgods.com','zovdrakona.ru','bc6.ru','moc.efil-triv','devilwars.ru','romewar.ru','gamex.wmsite.ru','tars.x7p.ru',
'lords.bc6.ru','benzik40','www.7fu.ru','www.kaktotak.ru','baldur.ru','77.72.131.108','newwords.in','genesyx.ru',
'oldcombat.net','mast.wmsite.ru','reign-of-warriors.com','damnedbk.com','ereality.ru','olbdk.com','devilwar.co.cc',
'tankionline.com','newacap.ru','worldoffights.net','alinar.ru','icecity.evolutions.ru','xaosclub.com','oldbk.info',
'clubbk.ru','dammee.bget.ru ','boyci.com','combats.okis.ru','nworld.org','combats3.ru','novoe.ucoz.ro','nbk-live.com',
'mirsmexa.livejournal.com','uabk.ru',
'combbats3.ru','townwars.ru','siteofcity.ru','xgame.wmsite.ru','last-war.net','combatxd.ru','acombats.ru','nuibk.ru',
'xcomb.bget.ru','c0mbatz.biz','www.lostworlds.lv','genesyx.ru',
'shadowworl.ru','celestia.com.ua','vkobatse.ru','apeha.ru','realcombats.com','xanstva.com','neverfate.ru','combats-club.ru',
'pebk.ucoz.es','frog.at.ua','sexyva.bget.ru',
'dwar.ru','neobk.bget.ru','pecm.do.am','combatxd.bget.ru','coombats.com','rome-war.com.ua','testus.su','warages.com','bk-world.ru','wekings.play.tegos.ru',
'capitallcity.com','newabk1.ru','timeage.ru','new-abk.com','warcross.ru','mixfight.3dn.ru','bklord.bget.ru','gold-bk.com','x-combat.ru','chaoswars.ru','game.ws-art.ru',
'darkcombats.net','empireofgods.net','combatsworl','rebk.my1.ru','conatz.com','empire.cc.ua','combat3.bget.ru','warbk.ru','commbats.com','kombatz','lastlands',
'rebk.at.ua','heroeswm.ru','lyksorbk.at.ua','realbk.do.am','acres-hope.ru','mofhe.ru','mcombats.ru','lyksorbk.at.ua','regaugra.at.ua','way-warrior.ltd.ua','nobk.biz',
'legioners.com','new-bk.com','carnage.ru','venom-deniz.com','combats.at.ua','instinkt.ru','lost-bk.com','dgame.ru','chaosroad.com','lastcombats.ucoz.ua','acombats.com',
'onlinewar.com.ua','moswar.ru','bkw.do.am','abk-world.hdd1.ru','old-knights.com','boici-bk.ru','arenabk.com','realbk2.blox.ua','combats-life.ru','real-bk2.do.am','s1.sfgame.ru',
'mycombats.com','meydan.az','ocombats.ru','newcombats.com','real-combats.com','bk-lend.ru','x-combats.ru','c0mbats.com','new-fc.ru','oldiow.ru','mycommbats.com','combatsbk.com',
'kazbk.kz','ecombats','newbk2','cossacs.clan.su','combatz.com',
'oldcap.ru','kombats.ru','worldofcombats.ru','zaturb.bget.ru','combatss.ru','combats2','newabk.su','virt-life.com','virt-life.ru','virt-life.net','virt life.com','combats2.com','combats2.ru',
'combats2.net','combatts.okis.ru','blowbk.ru','blowbk.com','blowbk.net','cwars.ru','cwars.com','cwars.net',
'acombatz.ru','acombatz.com','acombatz.net','worldbk.com','worldbk.ru','worldbk.net',
'realbk2.ru','realbk2.com','realbk2.net','lastcombats.com','lastcombats.ru','lastcombats.net',
'ardaniya.ru','ardaniya.com','ardaniya.net','ecombats.com','ecombats.ru','ecombats.net',
'zaturb.bget','cool.lya','bkold.com','escilon.ru',
'realbk2.com','realbk2.ru','realbk2.net','fdworlds.com','fdworlds.ru','fdworlds.net',
'nobk.jino.ru','capbk.com','capbk.ru','capbk.net','alone-islands.com','alone-islands.ru','alone-islands.net',
'old-combats.com','old-combats.ru','old-combats.net','lfight.com',
'bk-old.com','bk-old.ru','bk-old.net','bkold.com','bkold.ru','bkold.net',
'ccombats.ru','ccombats.com','oldcombats.com','oldcombats.ru','oldcombats.net','oldcombats.info',
'bkwar.com','bkwar.ru','bkwar.net', 'oldbk.ru','userbk.ru', 'streets.world', 'oldbk.today');
?>