<?php
/**
 * Created by PhpStorm.
 * User: me
 * Date: 13.12.16
 * Time: 20:45
 */

namespace components\Controller\encicl;


use components\Component\Slim\Slim;
use components\Controller\_base\BaseEnciclController;
use components\Model\Cshop;
use components\Model\Eshop;
use components\Model\Shop;
use components\Model\Magic;
use components\Object\Item;

class ItemController extends BaseEnciclController
{
	protected $item;

	public function __construct(Slim $container, $item)
	{
		$this->item = $item;
		parent::__construct($container, 'index');
	}

    protected function beforeAction($action)
    {
        $this->loadCssAndScripts();
        return parent::beforeAction($action); //TODO: Change the autogenerated stub
    }

	public function indexAction()
	{
		if(!$this->item) {
			return;
		}

		$img = $this->item;
		if ((strpos($this->item, ".png") === FALSE )) {
			$img = $this->item . ".gif";
		}
		if(!($Item = $this->getItem($img))) {
			return $this->render('itemnotfound');
		}
		$this->title = sprintf('%s | Бойцовский клуб ОЛДБК', $Item->name);

		$ItemObj = new Item();
		$ItemObj->item = $Item;
		if ($ItemObj->item->magic > 0) {
			$ItemObj->magic = (Magic::find('id = ?', array($ItemObj->item->magic)))->asModel();
		} elseif ($ItemObj->item->includemagic > 0) {
			$ItemObj->incmagic = (Magic::find('id = ?', array($ItemObj->item->includemagic)))->asModel();
		}


		$img_title = str_replace('.gif', '', $Item->img);
		$img = sprintf('https://i.oldbk.com/i/sh/big/'.$img_title.'_big.gif');
		$img2 = sprintf('https://i.oldbk.com/i/sh/big/'.$img_title.'_big.jpg');
		if(file_exists($img)) {
			$ItemObj->img_big = $img;
		} elseif(file_exists($img2)) {
			$ItemObj->img_big = $img2;
		} elseif($Item->img_big != '') {
			$ItemObj->img_big = sprintf('https://i.oldbk.com/i/sh/%s', $Item->img_big);
		} else {
			$ItemObj->img_big = 'https://i.oldbk.com/i/sh/big/nofoto_big.gif';
		}

		$this->render('item', array(
			'Item' => $ItemObj,
		));
	}

	private function getItem($img)
	{
		switch (true) {
			case strpos($img, "art_") === FALSE:
				$Item = Shop::find('img = ?', array($img))->asModel();
				if($Item) {
					return $Item;
				}

				$Item = Shop::find('img_big = ?', array($img))->asModel();
				if($Item) {
					return $Item;
				}

				$Item = Eshop::find('img = ?', array($img))->asModel();
				if($Item) {
					return $Item;
				}

				$Item = Cshop::find('img = ?', array($img))->asModel();
				if($Item) {
					return $Item;
				}
				break;
			case strpos($img, "elka_art_") !== FALSE:
				return Eshop::find('img = ?', array($img))->asModel();
				break;
		}

		return null;
	}
}