<?php
/**
 * Created by PhpStorm.
 * User: me
 * Date: 23.10.2018
 * Time: 16:06
 */

namespace components\Controller\street;


use components\Controller\_base\MainController;

class BaseStreetController extends MainController
{
	public $layout = 'main2';

	protected $movetime = 4; //4 sec

	public function beforeAction($action)
	{
		$r = parent::beforeAction($action); // TODO: Change the autogenerated stub
		if($this->user->battle != 0) {
			$this->redirect('/fbattle.php');
		}

		return $r;
	}

	protected function getControllerId()
	{
		$ref = (new \ReflectionClass($this));
		$className = str_replace('controller', '', strtolower($ref->getShortName()));

		return sprintf('street/%s', $className);
	}
}